package com.eurobuddha.statenft;

import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.Test;

import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.KeyFactory;
import java.security.MessageDigest;
import java.security.PublicKey;
import java.security.Signature;
import java.security.spec.MGF1ParameterSpec;
import java.security.spec.PSSParameterSpec;
import java.security.spec.RSAPublicKeySpec;
import java.util.Arrays;
import java.util.Base64;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

/** Pins Ans104 against golden fixtures generated by the reference implementation
 *  (arbundles) — see test/fixtures/arweave/generate.mjs. RSA-PSS is salted, so
 *  signatures are never byte-compared: the deterministic deepHash digest and Avro
 *  bytes are pinned, and signatures are cross-verified in both directions. */
public class Ans104Test {

    private static JSONObject fixtures() throws Exception {
        String p = System.getProperty("user.dir");   // android/app
        java.io.File f = new java.io.File(p, "../../test/fixtures/arweave/ans104.json");
        return new JSONObject(new String(Files.readAllBytes(Paths.get(f.getCanonicalPath())),
                java.nio.charset.StandardCharsets.UTF_8));
    }

    private static String[][] tagsOf(JSONArray a) throws Exception {
        String[][] tags = new String[a.length()][];
        for (int i = 0; i < a.length(); i++) {
            JSONObject t = a.getJSONObject(i);
            tags[i] = new String[]{ t.getString("name"), t.getString("value") };
        }
        return tags;
    }

    private static PublicKey publicKeyOf(JSONObject jwk) throws Exception {
        return KeyFactory.getInstance("RSA").generatePublic(new RSAPublicKeySpec(
                new BigInteger(1, Ans104.b64uDecode(jwk.getString("n"))),
                new BigInteger(1, Ans104.b64uDecode(jwk.getString("e")))));
    }

    private static boolean pssVerify(PublicKey pub, byte[] msg, byte[] sig) throws Exception {
        Signature s = Ans104.pss();
        s.initVerify(pub);
        s.update(msg);
        return s.verify(sig);
    }

    @Test public void avroTagsMatchReferenceBytes() throws Exception {
        JSONObject fx = fixtures();
        JSONArray cases = fx.getJSONArray("cases");
        for (int i = 0; i < cases.length(); i++) {
            JSONObject c = cases.getJSONObject(i);
            assertArrayEquals(c.getString("desc"),
                    Base64.getDecoder().decode(c.getString("tagsAvro_b64")),
                    Ans104.avroTags(tagsOf(c.getJSONArray("tags"))));
        }
    }

    @Test public void deepHashMatchesReferenceDigest() throws Exception {
        JSONObject fx = fixtures();
        Ans104.Jwk jwk = Ans104.parseJwk(fx.getJSONObject("jwk").toString());
        JSONArray cases = fx.getJSONArray("cases");
        for (int i = 0; i < cases.length(); i++) {
            JSONObject c = cases.getJSONObject(i);
            byte[] data = Base64.getDecoder().decode(c.getString("data_b64"));
            byte[] tagsAvro = Ans104.avroTags(tagsOf(c.getJSONArray("tags")));
            byte[] digest = Ans104.deepHashDataItem(jwk.owner, null, null, tagsAvro, data);
            StringBuilder hex = new StringBuilder();
            for (byte b : digest) hex.append(String.format("%02x", b));
            assertEquals(c.getString("desc"), c.getString("deepHash_hex"), hex.toString());
        }
    }

    /** Parse arbundles' signed items, verify their signatures with Java's RSA-PSS,
     *  and re-derive their ids — proves both the digest and the layout offsets. */
    @Test public void crossImplVerifyReferenceItems() throws Exception {
        JSONObject fx = fixtures();
        PublicKey pub = publicKeyOf(fx.getJSONObject("jwk"));
        JSONArray cases = fx.getJSONArray("cases");
        for (int i = 0; i < cases.length(); i++) {
            JSONObject c = cases.getJSONObject(i);
            byte[] raw = Base64.getDecoder().decode(c.getString("nodeSignedItem_b64"));
            assertEquals(c.getString("desc") + ": sigType", 1, (raw[0] & 0xFF) | ((raw[1] & 0xFF) << 8));
            byte[] sig = Arrays.copyOfRange(raw, 2, 514);
            byte[] owner = Arrays.copyOfRange(raw, 514, 1026);
            assertEquals(c.getString("desc") + ": target absent", 0, raw[1026]);
            assertEquals(c.getString("desc") + ": anchor absent", 0, raw[1027]);
            long tagCount = 0, tagBytes = 0;
            for (int b = 0; b < 8; b++) tagCount |= (long) (raw[1028 + b] & 0xFF) << (8 * b);
            for (int b = 0; b < 8; b++) tagBytes |= (long) (raw[1036 + b] & 0xFF) << (8 * b);
            assertEquals(c.getString("desc") + ": tag count", c.getJSONArray("tags").length(), tagCount);
            byte[] tagsAvro = Arrays.copyOfRange(raw, 1044, 1044 + (int) tagBytes);
            byte[] data = Arrays.copyOfRange(raw, 1044 + (int) tagBytes, raw.length);
            assertArrayEquals(c.getString("desc") + ": data",
                    Base64.getDecoder().decode(c.getString("data_b64")), data);
            byte[] digest = Ans104.deepHashDataItem(owner, null, null, tagsAvro, data);
            assertTrue(c.getString("desc") + ": reference signature verifies in Java",
                    pssVerify(pub, digest, sig));
            assertEquals(c.getString("desc") + ": id derivation", c.getString("nodeSignedId"),
                    Ans104.b64u(MessageDigest.getInstance("SHA-256").digest(sig)));
        }
    }

    /** Our own signed items: verify signature, id invariant, and binary layout
     *  byte-identical to the reference apart from the (salted) signature. */
    @Test public void signThenVerifyOwnItems() throws Exception {
        JSONObject fx = fixtures();
        Ans104.Jwk jwk = Ans104.parseJwk(fx.getJSONObject("jwk").toString());
        PublicKey pub = publicKeyOf(fx.getJSONObject("jwk"));
        JSONArray cases = fx.getJSONArray("cases");
        for (int i = 0; i < cases.length(); i++) {
            JSONObject c = cases.getJSONObject(i);
            byte[] data = Base64.getDecoder().decode(c.getString("data_b64"));
            String[][] tags = tagsOf(c.getJSONArray("tags"));
            Ans104.DataItem item = Ans104.createAndSign(jwk, data, tags);

            byte[] ref = Base64.getDecoder().decode(c.getString("nodeSignedItem_b64"));
            assertEquals(c.getString("desc") + ": total length", ref.length, item.totalLength());
            java.io.ByteArrayOutputStream bos = new java.io.ByteArrayOutputStream();
            item.writeTo(bos);
            byte[] mine = bos.toByteArray();
            // everything outside the 512-byte signature window [2,514) must match the reference
            assertArrayEquals(c.getString("desc") + ": prefix", Arrays.copyOfRange(ref, 0, 2), Arrays.copyOfRange(mine, 0, 2));
            assertArrayEquals(c.getString("desc") + ": owner+tags+data",
                    Arrays.copyOfRange(ref, 514, ref.length), Arrays.copyOfRange(mine, 514, mine.length));

            byte[] sig = Arrays.copyOfRange(mine, 2, 514);
            byte[] digest = Ans104.deepHashDataItem(jwk.owner, null, null, Ans104.avroTags(tags), data);
            assertTrue(c.getString("desc") + ": own signature verifies", pssVerify(pub, digest, sig));
            assertEquals(c.getString("desc") + ": id invariant",
                    Ans104.b64u(MessageDigest.getInstance("SHA-256").digest(sig)), item.id);
        }
    }

    @Test public void addressMatchesReference() throws Exception {
        JSONObject fx = fixtures();
        assertEquals(fx.getString("address"), Ans104.addressFromJwk(fx.getJSONObject("jwk").toString()));
    }

    @Test public void generateParseSignRoundTrip() throws Exception {
        String json = Ans104.generateJwkJson();
        Ans104.Jwk jwk = Ans104.parseJwk(json);
        assertEquals(512, jwk.owner.length);
        byte[] data = "fresh wallet round trip".getBytes("UTF-8");
        Ans104.DataItem item = Ans104.createAndSign(jwk, data, new String[][]{{ "Content-Type", "text/plain" }});
        PublicKey pub = publicKeyOf(new JSONObject(json));
        java.io.ByteArrayOutputStream bos = new java.io.ByteArrayOutputStream();
        item.writeTo(bos);
        byte[] sig = Arrays.copyOfRange(bos.toByteArray(), 2, 514);
        byte[] digest = Ans104.deepHashDataItem(jwk.owner, null, null,
                Ans104.avroTags(new String[][]{{ "Content-Type", "text/plain" }}), data);
        assertTrue(pssVerify(pub, digest, sig));
        assertEquals(43, Ans104.addressFromJwk(json).length());   // b64url(32 bytes), no padding
    }
}
