plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.eurobuddha.statenft'
    compileSdk 36

    defaultConfig {
        applicationId "com.eurobuddha.statenft"
        minSdk 28
        targetSdk 35
        versionCode 408
        versionName "0.4.8"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation files('libs/minimaapi.aar')
    implementation 'com.caverock:androidsvg-aar:1.4'
    implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.20.0'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
}
